import * as HeroIcons from '@heroicons/react/24/outline'
import type { ComponentType, SVGProps } from 'react'

// All available heroicons
export const iconOptions = [
  { label: 'Academic Cap', value: 'AcademicCapIcon' },
  { label: 'Adjustments Horizontal', value: 'AdjustmentsHorizontalIcon' },
  { label: 'Adjustments Vertical', value: 'AdjustmentsVerticalIcon' },
  { label: 'Archive Box Arrow Down', value: 'ArchiveBoxArrowDownIcon' },
  { label: 'Archive Box X Mark', value: 'ArchiveBoxXMarkIcon' },
  { label: 'Archive Box', value: 'ArchiveBoxIcon' },
  { label: 'Arrow Down Circle', value: 'ArrowDownCircleIcon' },
  { label: 'Arrow Down Left', value: 'ArrowDownLeftIcon' },
  { label: 'Arrow Down On Square Stack', value: 'ArrowDownOnSquareStackIcon' },
  { label: 'Arrow Down On Square', value: 'ArrowDownOnSquareIcon' },
  { label: 'Arrow Down Right', value: 'ArrowDownRightIcon' },
  { label: 'Arrow Down Tray', value: 'ArrowDownTrayIcon' },
  { label: 'Arrow Down', value: 'ArrowDownIcon' },
  { label: 'Arrow Left Circle', value: 'ArrowLeftCircleIcon' },
  { label: 'Arrow Left End On Rectangle', value: 'ArrowLeftEndOnRectangleIcon' },
  { label: 'Arrow Left On Rectangle', value: 'ArrowLeftOnRectangleIcon' },
  { label: 'Arrow Left Start On Rectangle', value: 'ArrowLeftStartOnRectangleIcon' },
  { label: 'Arrow Left', value: 'ArrowLeftIcon' },
  { label: 'Arrow Long Down', value: 'ArrowLongDownIcon' },
  { label: 'Arrow Long Left', value: 'ArrowLongLeftIcon' },
  { label: 'Arrow Long Right', value: 'ArrowLongRightIcon' },
  { label: 'Arrow Long Up', value: 'ArrowLongUpIcon' },
  { label: 'Arrow Path Rounded Square', value: 'ArrowPathRoundedSquareIcon' },
  { label: 'Arrow Path', value: 'ArrowPathIcon' },
  { label: 'Arrow Right Circle', value: 'ArrowRightCircleIcon' },
  { label: 'Arrow Right End On Rectangle', value: 'ArrowRightEndOnRectangleIcon' },
  { label: 'Arrow Right On Rectangle', value: 'ArrowRightOnRectangleIcon' },
  { label: 'Arrow Right Start On Rectangle', value: 'ArrowRightStartOnRectangleIcon' },
  { label: 'Arrow Right', value: 'ArrowRightIcon' },
  { label: 'Arrow Small Down', value: 'ArrowSmallDownIcon' },
  { label: 'Arrow Small Left', value: 'ArrowSmallLeftIcon' },
  { label: 'Arrow Small Right', value: 'ArrowSmallRightIcon' },
  { label: 'Arrow Small Up', value: 'ArrowSmallUpIcon' },
  { label: 'Arrow Top Right On Square', value: 'ArrowTopRightOnSquareIcon' },
  { label: 'Arrow Trending Down', value: 'ArrowTrendingDownIcon' },
  { label: 'Arrow Trending Up', value: 'ArrowTrendingUpIcon' },
  { label: 'Arrow Turn Down Left', value: 'ArrowTurnDownLeftIcon' },
  { label: 'Arrow Turn Down Right', value: 'ArrowTurnDownRightIcon' },
  { label: 'Arrow Turn Left Down', value: 'ArrowTurnLeftDownIcon' },
  { label: 'Arrow Turn Left Up', value: 'ArrowTurnLeftUpIcon' },
  { label: 'Arrow Turn Right Down', value: 'ArrowTurnRightDownIcon' },
  { label: 'Arrow Turn Right Up', value: 'ArrowTurnRightUpIcon' },
  { label: 'Arrow Turn Up Left', value: 'ArrowTurnUpLeftIcon' },
  { label: 'Arrow Turn Up Right', value: 'ArrowTurnUpRightIcon' },
  { label: 'Arrow Up Circle', value: 'ArrowUpCircleIcon' },
  { label: 'Arrow Up Left', value: 'ArrowUpLeftIcon' },
  { label: 'Arrow Up On Square Stack', value: 'ArrowUpOnSquareStackIcon' },
  { label: 'Arrow Up On Square', value: 'ArrowUpOnSquareIcon' },
  { label: 'Arrow Up Right', value: 'ArrowUpRightIcon' },
  { label: 'Arrow Up Tray', value: 'ArrowUpTrayIcon' },
  { label: 'Arrow Up', value: 'ArrowUpIcon' },
  { label: 'Arrow Uturn Down', value: 'ArrowUturnDownIcon' },
  { label: 'Arrow Uturn Left', value: 'ArrowUturnLeftIcon' },
  { label: 'Arrow Uturn Right', value: 'ArrowUturnRightIcon' },
  { label: 'Arrow Uturn Up', value: 'ArrowUturnUpIcon' },
  { label: 'Arrows Pointing In', value: 'ArrowsPointingInIcon' },
  { label: 'Arrows Pointing Out', value: 'ArrowsPointingOutIcon' },
  { label: 'Arrows Right Left', value: 'ArrowsRightLeftIcon' },
  { label: 'Arrows Up Down', value: 'ArrowsUpDownIcon' },
  { label: 'At Symbol', value: 'AtSymbolIcon' },
  { label: 'Backspace', value: 'BackspaceIcon' },
  { label: 'Backward', value: 'BackwardIcon' },
  { label: 'Banknotes', value: 'BanknotesIcon' },
  { label: 'Bars 2', value: 'Bars2Icon' },
  { label: 'Bars 3 Bottom Left', value: 'Bars3BottomLeftIcon' },
  { label: 'Bars 3 Bottom Right', value: 'Bars3BottomRightIcon' },
  { label: 'Bars 3 Center Left', value: 'Bars3CenterLeftIcon' },
  { label: 'Bars 3', value: 'Bars3Icon' },
  { label: 'Bars 4', value: 'Bars4Icon' },
  { label: 'Bars Arrow Down', value: 'BarsArrowDownIcon' },
  { label: 'Bars Arrow Up', value: 'BarsArrowUpIcon' },
  { label: 'Battery 0', value: 'Battery0Icon' },
  { label: 'Battery 100', value: 'Battery100Icon' },
  { label: 'Battery 50', value: 'Battery50Icon' },
  { label: 'Beaker', value: 'BeakerIcon' },
  { label: 'Bell Alert', value: 'BellAlertIcon' },
  { label: 'Bell Slash', value: 'BellSlashIcon' },
  { label: 'Bell Snooze', value: 'BellSnoozeIcon' },
  { label: 'Bell', value: 'BellIcon' },
  { label: 'Bold', value: 'BoldIcon' },
  { label: 'Bolt Slash', value: 'BoltSlashIcon' },
  { label: 'Bolt', value: 'BoltIcon' },
  { label: 'Book Open', value: 'BookOpenIcon' },
  { label: 'Bookmark Slash', value: 'BookmarkSlashIcon' },
  { label: 'Bookmark Square', value: 'BookmarkSquareIcon' },
  { label: 'Bookmark', value: 'BookmarkIcon' },
  { label: 'Briefcase', value: 'BriefcaseIcon' },
  { label: 'Bug Ant', value: 'BugAntIcon' },
  { label: 'Building Library', value: 'BuildingLibraryIcon' },
  { label: 'Building Office 2', value: 'BuildingOffice2Icon' },
  { label: 'Building Office', value: 'BuildingOfficeIcon' },
  { label: 'Building Storefront', value: 'BuildingStorefrontIcon' },
  { label: 'Cake', value: 'CakeIcon' },
  { label: 'Calculator', value: 'CalculatorIcon' },
  { label: 'Calendar Date Range', value: 'CalendarDateRangeIcon' },
  { label: 'Calendar Days', value: 'CalendarDaysIcon' },
  { label: 'Calendar', value: 'CalendarIcon' },
  { label: 'Camera', value: 'CameraIcon' },
  { label: 'Chart Bar Square', value: 'ChartBarSquareIcon' },
  { label: 'Chart Bar', value: 'ChartBarIcon' },
  { label: 'Chart Pie', value: 'ChartPieIcon' },
  { label: 'Chat Bubble Bottom Center Text', value: 'ChatBubbleBottomCenterTextIcon' },
  { label: 'Chat Bubble Bottom Center', value: 'ChatBubbleBottomCenterIcon' },
  { label: 'Chat Bubble Left Ellipsis', value: 'ChatBubbleLeftEllipsisIcon' },
  { label: 'Chat Bubble Left Right', value: 'ChatBubbleLeftRightIcon' },
  { label: 'Chat Bubble Left', value: 'ChatBubbleLeftIcon' },
  { label: 'Chat Bubble Oval Left Ellipsis', value: 'ChatBubbleOvalLeftEllipsisIcon' },
  { label: 'Chat Bubble Oval Left', value: 'ChatBubbleOvalLeftIcon' },
  { label: 'Check Badge', value: 'CheckBadgeIcon' },
  { label: 'Check Circle', value: 'CheckCircleIcon' },
  { label: 'Check', value: 'CheckIcon' },
  { label: 'Chevron Double Down', value: 'ChevronDoubleDownIcon' },
  { label: 'Chevron Double Left', value: 'ChevronDoubleLeftIcon' },
  { label: 'Chevron Double Right', value: 'ChevronDoubleRightIcon' },
  { label: 'Chevron Double Up', value: 'ChevronDoubleUpIcon' },
  { label: 'Chevron Down', value: 'ChevronDownIcon' },
  { label: 'Chevron Left', value: 'ChevronLeftIcon' },
  { label: 'Chevron Right', value: 'ChevronRightIcon' },
  { label: 'Chevron Up Down', value: 'ChevronUpDownIcon' },
  { label: 'Chevron Up', value: 'ChevronUpIcon' },
  { label: 'Circle Stack', value: 'CircleStackIcon' },
  { label: 'Clipboard Document Check', value: 'ClipboardDocumentCheckIcon' },
  { label: 'Clipboard Document List', value: 'ClipboardDocumentListIcon' },
  { label: 'Clipboard Document', value: 'ClipboardDocumentIcon' },
  { label: 'Clipboard', value: 'ClipboardIcon' },
  { label: 'Clock', value: 'ClockIcon' },
  { label: 'Cloud Arrow Down', value: 'CloudArrowDownIcon' },
  { label: 'Cloud Arrow Up', value: 'CloudArrowUpIcon' },
  { label: 'Cloud', value: 'CloudIcon' },
  { label: 'Code Bracket Square', value: 'CodeBracketSquareIcon' },
  { label: 'Code Bracket', value: 'CodeBracketIcon' },
  { label: 'Cog 6 Tooth', value: 'Cog6ToothIcon' },
  { label: 'Cog 8 Tooth', value: 'Cog8ToothIcon' },
  { label: 'Cog', value: 'CogIcon' },
  { label: 'Command Line', value: 'CommandLineIcon' },
  { label: 'Computer Desktop', value: 'ComputerDesktopIcon' },
  { label: 'Cpu Chip', value: 'CpuChipIcon' },
  { label: 'Credit Card', value: 'CreditCardIcon' },
  { label: 'Cube Transparent', value: 'CubeTransparentIcon' },
  { label: 'Cube', value: 'CubeIcon' },
  { label: 'Currency Bangladeshi', value: 'CurrencyBangladeshiIcon' },
  { label: 'Currency Dollar', value: 'CurrencyDollarIcon' },
  { label: 'Currency Euro', value: 'CurrencyEuroIcon' },
  { label: 'Currency Pound', value: 'CurrencyPoundIcon' },
  { label: 'Currency Rupee', value: 'CurrencyRupeeIcon' },
  { label: 'Currency Yen', value: 'CurrencyYenIcon' },
  { label: 'Cursor Arrow Rays', value: 'CursorArrowRaysIcon' },
  { label: 'Cursor Arrow Ripple', value: 'CursorArrowRippleIcon' },
  { label: 'Device Phone Mobile', value: 'DevicePhoneMobileIcon' },
  { label: 'Device Tablet', value: 'DeviceTabletIcon' },
  { label: 'Divide', value: 'DivideIcon' },
  { label: 'Document Arrow Down', value: 'DocumentArrowDownIcon' },
  { label: 'Document Arrow Up', value: 'DocumentArrowUpIcon' },
  { label: 'Document Chart Bar', value: 'DocumentChartBarIcon' },
  { label: 'Document Check', value: 'DocumentCheckIcon' },
  { label: 'Document Currency Bangladeshi', value: 'DocumentCurrencyBangladeshiIcon' },
  { label: 'Document Currency Dollar', value: 'DocumentCurrencyDollarIcon' },
  { label: 'Document Currency Euro', value: 'DocumentCurrencyEuroIcon' },
  { label: 'Document Currency Pound', value: 'DocumentCurrencyPoundIcon' },
  { label: 'Document Currency Rupee', value: 'DocumentCurrencyRupeeIcon' },
  { label: 'Document Currency Yen', value: 'DocumentCurrencyYenIcon' },
  { label: 'Document Duplicate', value: 'DocumentDuplicateIcon' },
  { label: 'Document Magnifying Glass', value: 'DocumentMagnifyingGlassIcon' },
  { label: 'Document Minus', value: 'DocumentMinusIcon' },
  { label: 'Document Plus', value: 'DocumentPlusIcon' },
  { label: 'Document Text', value: 'DocumentTextIcon' },
  { label: 'Document', value: 'DocumentIcon' },
  { label: 'Ellipsis Horizontal Circle', value: 'EllipsisHorizontalCircleIcon' },
  { label: 'Ellipsis Horizontal', value: 'EllipsisHorizontalIcon' },
  { label: 'Ellipsis Vertical', value: 'EllipsisVerticalIcon' },
  { label: 'Envelope Open', value: 'EnvelopeOpenIcon' },
  { label: 'Envelope', value: 'EnvelopeIcon' },
  { label: 'Equals', value: 'EqualsIcon' },
  { label: 'Exclamation Circle', value: 'ExclamationCircleIcon' },
  { label: 'Exclamation Triangle', value: 'ExclamationTriangleIcon' },
  { label: 'Eye Dropper', value: 'EyeDropperIcon' },
  { label: 'Eye Slash', value: 'EyeSlashIcon' },
  { label: 'Eye', value: 'EyeIcon' },
  { label: 'Face Frown', value: 'FaceFrownIcon' },
  { label: 'Face Smile', value: 'FaceSmileIcon' },
  { label: 'Film', value: 'FilmIcon' },
  { label: 'Finger Print', value: 'FingerPrintIcon' },
  { label: 'Fire', value: 'FireIcon' },
  { label: 'Flag', value: 'FlagIcon' },
  { label: 'Folder Arrow Down', value: 'FolderArrowDownIcon' },
  { label: 'Folder Minus', value: 'FolderMinusIcon' },
  { label: 'Folder Open', value: 'FolderOpenIcon' },
  { label: 'Folder Plus', value: 'FolderPlusIcon' },
  { label: 'Folder', value: 'FolderIcon' },
  { label: 'Forward', value: 'ForwardIcon' },
  { label: 'Funnel', value: 'FunnelIcon' },
  { label: 'Gif', value: 'GifIcon' },
  { label: 'Gift Top', value: 'GiftTopIcon' },
  { label: 'Gift', value: 'GiftIcon' },
  { label: 'Globe Alt', value: 'GlobeAltIcon' },
  { label: 'Globe Americas', value: 'GlobeAmericasIcon' },
  { label: 'Globe Asia Australia', value: 'GlobeAsiaAustraliaIcon' },
  { label: 'Globe Europe Africa', value: 'GlobeEuropeAfricaIcon' },
  { label: 'H1', value: 'H1Icon' },
  { label: 'H2', value: 'H2Icon' },
  { label: 'H3', value: 'H3Icon' },
  { label: 'Hand Raised', value: 'HandRaisedIcon' },
  { label: 'Hand Thumb Down', value: 'HandThumbDownIcon' },
  { label: 'Hand Thumb Up', value: 'HandThumbUpIcon' },
  { label: 'Hashtag', value: 'HashtagIcon' },
  { label: 'Heart', value: 'HeartIcon' },
  { label: 'Home Modern', value: 'HomeModernIcon' },
  { label: 'Home', value: 'HomeIcon' },
  { label: 'Identification', value: 'IdentificationIcon' },
  { label: 'Inbox Arrow Down', value: 'InboxArrowDownIcon' },
  { label: 'Inbox Stack', value: 'InboxStackIcon' },
  { label: 'Inbox', value: 'InboxIcon' },
  { label: 'Information Circle', value: 'InformationCircleIcon' },
  { label: 'Italic', value: 'ItalicIcon' },
  { label: 'Key', value: 'KeyIcon' },
  { label: 'Language', value: 'LanguageIcon' },
  { label: 'Lifebuoy', value: 'LifebuoyIcon' },
  { label: 'Light Bulb', value: 'LightBulbIcon' },
  { label: 'Link Slash', value: 'LinkSlashIcon' },
  { label: 'Link', value: 'LinkIcon' },
  { label: 'List Bullet', value: 'ListBulletIcon' },
  { label: 'Lock Closed', value: 'LockClosedIcon' },
  { label: 'Lock Open', value: 'LockOpenIcon' },
  { label: 'Magnifying Glass Circle', value: 'MagnifyingGlassCircleIcon' },
  { label: 'Magnifying Glass Minus', value: 'MagnifyingGlassMinusIcon' },
  { label: 'Magnifying Glass Plus', value: 'MagnifyingGlassPlusIcon' },
  { label: 'Magnifying Glass', value: 'MagnifyingGlassIcon' },
  { label: 'Map Pin', value: 'MapPinIcon' },
  { label: 'Map', value: 'MapIcon' },
  { label: 'Megaphone', value: 'MegaphoneIcon' },
  { label: 'Microphone', value: 'MicrophoneIcon' },
  { label: 'Minus Circle', value: 'MinusCircleIcon' },
  { label: 'Minus Small', value: 'MinusSmallIcon' },
  { label: 'Minus', value: 'MinusIcon' },
  { label: 'Moon', value: 'MoonIcon' },
  { label: 'Musical Note', value: 'MusicalNoteIcon' },
  { label: 'Newspaper', value: 'NewspaperIcon' },
  { label: 'No Symbol', value: 'NoSymbolIcon' },
  { label: 'Numbered List', value: 'NumberedListIcon' },
  { label: 'Paint Brush', value: 'PaintBrushIcon' },
  { label: 'Paper Airplane', value: 'PaperAirplaneIcon' },
  { label: 'Paper Clip', value: 'PaperClipIcon' },
  { label: 'Pause Circle', value: 'PauseCircleIcon' },
  { label: 'Pause', value: 'PauseIcon' },
  { label: 'Pencil Square', value: 'PencilSquareIcon' },
  { label: 'Pencil', value: 'PencilIcon' },
  { label: 'Percent Badge', value: 'PercentBadgeIcon' },
  { label: 'Phone Arrow Down Left', value: 'PhoneArrowDownLeftIcon' },
  { label: 'Phone Arrow Up Right', value: 'PhoneArrowUpRightIcon' },
  { label: 'Phone X Mark', value: 'PhoneXMarkIcon' },
  { label: 'Phone', value: 'PhoneIcon' },
  { label: 'Photo', value: 'PhotoIcon' },
  { label: 'Play Circle', value: 'PlayCircleIcon' },
  { label: 'Play Pause', value: 'PlayPauseIcon' },
  { label: 'Play', value: 'PlayIcon' },
  { label: 'Plus Circle', value: 'PlusCircleIcon' },
  { label: 'Plus Small', value: 'PlusSmallIcon' },
  { label: 'Plus', value: 'PlusIcon' },
  { label: 'Power', value: 'PowerIcon' },
  { label: 'Presentation Chart Bar', value: 'PresentationChartBarIcon' },
  { label: 'Presentation Chart Line', value: 'PresentationChartLineIcon' },
  { label: 'Printer', value: 'PrinterIcon' },
  { label: 'Puzzle Piece', value: 'PuzzlePieceIcon' },
  { label: 'Qr Code', value: 'QrCodeIcon' },
  { label: 'Question Mark Circle', value: 'QuestionMarkCircleIcon' },
  { label: 'Queue List', value: 'QueueListIcon' },
  { label: 'Radio', value: 'RadioIcon' },
  { label: 'Receipt Percent', value: 'ReceiptPercentIcon' },
  { label: 'Receipt Refund', value: 'ReceiptRefundIcon' },
  { label: 'Rectangle Group', value: 'RectangleGroupIcon' },
  { label: 'Rectangle Stack', value: 'RectangleStackIcon' },
  { label: 'Rocket Launch', value: 'RocketLaunchIcon' },
  { label: 'Rss', value: 'RssIcon' },
  { label: 'Scale', value: 'ScaleIcon' },
  { label: 'Scissors', value: 'ScissorsIcon' },
  { label: 'Server Stack', value: 'ServerStackIcon' },
  { label: 'Server', value: 'ServerIcon' },
  { label: 'Share', value: 'ShareIcon' },
  { label: 'Shield Check', value: 'ShieldCheckIcon' },
  { label: 'Shield Exclamation', value: 'ShieldExclamationIcon' },
  { label: 'Shopping Bag', value: 'ShoppingBagIcon' },
  { label: 'Shopping Cart', value: 'ShoppingCartIcon' },
  { label: 'Signal Slash', value: 'SignalSlashIcon' },
  { label: 'Signal', value: 'SignalIcon' },
  { label: 'Slash', value: 'SlashIcon' },
  { label: 'Sparkles', value: 'SparklesIcon' },
  { label: 'Speaker Wave', value: 'SpeakerWaveIcon' },
  { label: 'Speaker X Mark', value: 'SpeakerXMarkIcon' },
  { label: 'Square 2 Stack', value: 'Square2StackIcon' },
  { label: 'Square 3 Stack 3D', value: 'Square3Stack3DIcon' },
  { label: 'Squares 2X2', value: 'Squares2X2Icon' },
  { label: 'Squares Plus', value: 'SquaresPlusIcon' },
  { label: 'Star', value: 'StarIcon' },
  { label: 'Stop Circle', value: 'StopCircleIcon' },
  { label: 'Stop', value: 'StopIcon' },
  { label: 'Strikethrough', value: 'StrikethroughIcon' },
  { label: 'Sun', value: 'SunIcon' },
  { label: 'Swatch', value: 'SwatchIcon' },
  { label: 'Table Cells', value: 'TableCellsIcon' },
  { label: 'Tag', value: 'TagIcon' },
  { label: 'Ticket', value: 'TicketIcon' },
  { label: 'Trash', value: 'TrashIcon' },
  { label: 'Trophy', value: 'TrophyIcon' },
  { label: 'Truck', value: 'TruckIcon' },
  { label: 'Tv', value: 'TvIcon' },
  { label: 'Underline', value: 'UnderlineIcon' },
  { label: 'User Circle', value: 'UserCircleIcon' },
  { label: 'User Group', value: 'UserGroupIcon' },
  { label: 'User Minus', value: 'UserMinusIcon' },
  { label: 'User Plus', value: 'UserPlusIcon' },
  { label: 'User', value: 'UserIcon' },
  { label: 'Users', value: 'UsersIcon' },
  { label: 'Variable', value: 'VariableIcon' },
  { label: 'Video Camera Slash', value: 'VideoCameraSlashIcon' },
  { label: 'Video Camera', value: 'VideoCameraIcon' },
  { label: 'View Columns', value: 'ViewColumnsIcon' },
  { label: 'Viewfinder Circle', value: 'ViewfinderCircleIcon' },
  { label: 'Wallet', value: 'WalletIcon' },
  { label: 'Wifi', value: 'WifiIcon' },
  { label: 'Window', value: 'WindowIcon' },
  { label: 'Wrench Screwdriver', value: 'WrenchScrewdriverIcon' },
  { label: 'Wrench', value: 'WrenchIcon' },
  { label: 'X Circle', value: 'XCircleIcon' },
  { label: 'X Mark', value: 'XMarkIcon' },
] as const

export type IconName = (typeof iconOptions)[number]['value']

// Type-safe icon component getter
export const getIcon = (
  iconName: string | null | undefined,
): ComponentType<SVGProps<SVGSVGElement>> | null => {
  if (!iconName) return null

  // Type assertion needed because HeroIcons is a namespace
  const IconComponent = (HeroIcons as Record<string, ComponentType<SVGProps<SVGSVGElement>>>)[
    iconName
  ]

  return IconComponent || null
}
