/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tags: Tag;
    lab: Lab;
    posts: Post;
    projects: Project;
    'mux-video': MuxVideo;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    lab: LabSelect<false> | LabSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'mux-video': MuxVideoSelect<false> | MuxVideoSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Display name for the tag, e.g. "Next.js", "AI", "Design".
   */
  label: string;
  /**
   * Colour scheme for the tag. Maps to design token colours.
   */
  colour:
    | 'indigo'
    | 'blueSlate'
    | 'emerald'
    | 'teal'
    | 'amber'
    | 'rose'
    | 'brown'
    | 'olive'
    | 'purple'
    | 'cyan'
    | 'grey'
    | 'green'
    | 'violet';
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Tag;
  breadcrumbs?:
    | {
        doc?: (number | null) | Tag;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Display controls for /lab tools. Tool identity comes from code, route slug from CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lab".
 */
export interface Lab {
  id: number;
  /**
   * Stable code key from src/lib/lab/registry.ts used to map this entry.
   */
  toolKey: 'memory-card-storage-calc' | 'roast-my-website';
  enabled?: boolean | null;
  order?: number | null;
  kind?: ('tool' | 'app' | 'ai') | null;
  /**
   * Optional sidebar section override.
   */
  group?: ('ai' | 'apps' | 'tools') | null;
  /**
   * Display title shown in the lab sidebar and tool header.
   */
  title: string;
  /**
   * Badge tag shown in the lab sidebar for this tool.
   */
  primaryTag: number | Tag;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Short one-liner shown under the tool title.
   */
  description?: string | null;
  /**
   * Optional model label shown in tool header.
   */
  model?: string | null;
  /**
   * Optional expandable write-up shown below the tool.
   */
  writeUp?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional URL for a deeper blog post.
   */
  blogPostUrl?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Used in the browser tab, OG image, and post cards.
   */
  title: string;
  /**
   * 150 characters max. Shown on index cards and used as OG description.
   */
  excerpt?: string | null;
  /**
   * Main image for the post. Shown at the top of the post and on cards.
   */
  heroImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Up to 2 related posts shown at the bottom.
   */
  relatedPosts?: (number | Post)[] | null;
  /**
   * Tags for filtering on the posts page.
   */
  tags?: (number | Tag)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Auto-calculated from content word count (~200 wpm).
   */
  readTime?: number | null;
  /**
   * Auto-set on first publish. Can be overridden.
   */
  publishedAt?: string | null;
  /**
   * Pinned on /posts in the featured row. Only the two most recent featured posts are shown (by published date).
   */
  featured?: boolean | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Project name. Used in cards, OG images, and the browser tab.
   */
  title: string;
  /**
   * 120 characters max. Shown on the project card.
   */
  excerpt?: string | null;
  /**
   * The kind of project this is.
   */
  type: 'demo' | 'client' | 'experiment' | 'personal';
  /**
   * Whether the external project/app is live, archived, etc.
   */
  lifecycle: 'live' | 'in-progress' | 'archived';
  /**
   * Year the project was built or launched.
   */
  year?: number | null;
  /**
   * Main screenshot or cover image for the project.
   */
  heroImage: number | Media;
  /**
   * Additional slides: images, GIFs (Media), or Mux-hosted video. Drag to reorder.
   */
  gallery?:
    | {
        /**
         * Use Media for screenshots and GIFs; use Mux for hosted video.
         */
        slideType: 'media' | 'mux';
        image?: (number | null) | Media;
        muxVideo?: (number | null) | MuxVideo;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional longer write-up about the project.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Technologies used. Each entry has a name and its role in the project.
   */
  techStack?:
    | {
        name: string;
        /**
         * e.g. "framework", "styling", "deployment"
         */
        role: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL to the live project.
   */
  liveUrl?: string | null;
  /**
   * URL to the source code. Only shown for demo/experiment projects.
   */
  codeUrl?: string | null;
  /**
   * Shown on the project page as // role (e.g. Development & deployment).
   */
  role?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Tags for filtering on the projects page.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Featured projects appear on the homepage.
   */
  featured?: boolean | null;
  /**
   * Manual sort order. Lower numbers appear first.
   */
  order?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mux-video".
 */
export interface MuxVideo {
  id: number;
  /**
   * A unique title for this video that will help you identify it later.
   */
  title: string;
  assetId?: string | null;
  duration?: number | null;
  /**
   * Pick a timestamp (in seconds) from the video to be used as the poster image. When unset, defaults to the middle of the video.
   */
  posterTimestamp?: number | null;
  aspectRatio?: string | null;
  maxWidth?: number | null;
  maxHeight?: number | null;
  playbackOptions?:
    | {
        playbackId?: string | null;
        playbackPolicy?: ('signed' | 'public') | null;
        playbackUrl?: string | null;
        posterUrl?: string | null;
        gifUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            options: {
              label: string;
              icon:
                | 'AcademicCapIcon'
                | 'AdjustmentsHorizontalIcon'
                | 'AdjustmentsVerticalIcon'
                | 'ArchiveBoxArrowDownIcon'
                | 'ArchiveBoxXMarkIcon'
                | 'ArchiveBoxIcon'
                | 'ArrowDownCircleIcon'
                | 'ArrowDownLeftIcon'
                | 'ArrowDownOnSquareStackIcon'
                | 'ArrowDownOnSquareIcon'
                | 'ArrowDownRightIcon'
                | 'ArrowDownTrayIcon'
                | 'ArrowDownIcon'
                | 'ArrowLeftCircleIcon'
                | 'ArrowLeftEndOnRectangleIcon'
                | 'ArrowLeftOnRectangleIcon'
                | 'ArrowLeftStartOnRectangleIcon'
                | 'ArrowLeftIcon'
                | 'ArrowLongDownIcon'
                | 'ArrowLongLeftIcon'
                | 'ArrowLongRightIcon'
                | 'ArrowLongUpIcon'
                | 'ArrowPathRoundedSquareIcon'
                | 'ArrowPathIcon'
                | 'ArrowRightCircleIcon'
                | 'ArrowRightEndOnRectangleIcon'
                | 'ArrowRightOnRectangleIcon'
                | 'ArrowRightStartOnRectangleIcon'
                | 'ArrowRightIcon'
                | 'ArrowSmallDownIcon'
                | 'ArrowSmallLeftIcon'
                | 'ArrowSmallRightIcon'
                | 'ArrowSmallUpIcon'
                | 'ArrowTopRightOnSquareIcon'
                | 'ArrowTrendingDownIcon'
                | 'ArrowTrendingUpIcon'
                | 'ArrowTurnDownLeftIcon'
                | 'ArrowTurnDownRightIcon'
                | 'ArrowTurnLeftDownIcon'
                | 'ArrowTurnLeftUpIcon'
                | 'ArrowTurnRightDownIcon'
                | 'ArrowTurnRightUpIcon'
                | 'ArrowTurnUpLeftIcon'
                | 'ArrowTurnUpRightIcon'
                | 'ArrowUpCircleIcon'
                | 'ArrowUpLeftIcon'
                | 'ArrowUpOnSquareStackIcon'
                | 'ArrowUpOnSquareIcon'
                | 'ArrowUpRightIcon'
                | 'ArrowUpTrayIcon'
                | 'ArrowUpIcon'
                | 'ArrowUturnDownIcon'
                | 'ArrowUturnLeftIcon'
                | 'ArrowUturnRightIcon'
                | 'ArrowUturnUpIcon'
                | 'ArrowsPointingInIcon'
                | 'ArrowsPointingOutIcon'
                | 'ArrowsRightLeftIcon'
                | 'ArrowsUpDownIcon'
                | 'AtSymbolIcon'
                | 'BackspaceIcon'
                | 'BackwardIcon'
                | 'BanknotesIcon'
                | 'Bars2Icon'
                | 'Bars3BottomLeftIcon'
                | 'Bars3BottomRightIcon'
                | 'Bars3CenterLeftIcon'
                | 'Bars3Icon'
                | 'Bars4Icon'
                | 'BarsArrowDownIcon'
                | 'BarsArrowUpIcon'
                | 'Battery0Icon'
                | 'Battery100Icon'
                | 'Battery50Icon'
                | 'BeakerIcon'
                | 'BellAlertIcon'
                | 'BellSlashIcon'
                | 'BellSnoozeIcon'
                | 'BellIcon'
                | 'BoldIcon'
                | 'BoltSlashIcon'
                | 'BoltIcon'
                | 'BookOpenIcon'
                | 'BookmarkSlashIcon'
                | 'BookmarkSquareIcon'
                | 'BookmarkIcon'
                | 'BriefcaseIcon'
                | 'BugAntIcon'
                | 'BuildingLibraryIcon'
                | 'BuildingOffice2Icon'
                | 'BuildingOfficeIcon'
                | 'BuildingStorefrontIcon'
                | 'CakeIcon'
                | 'CalculatorIcon'
                | 'CalendarDateRangeIcon'
                | 'CalendarDaysIcon'
                | 'CalendarIcon'
                | 'CameraIcon'
                | 'ChartBarSquareIcon'
                | 'ChartBarIcon'
                | 'ChartPieIcon'
                | 'ChatBubbleBottomCenterTextIcon'
                | 'ChatBubbleBottomCenterIcon'
                | 'ChatBubbleLeftEllipsisIcon'
                | 'ChatBubbleLeftRightIcon'
                | 'ChatBubbleLeftIcon'
                | 'ChatBubbleOvalLeftEllipsisIcon'
                | 'ChatBubbleOvalLeftIcon'
                | 'CheckBadgeIcon'
                | 'CheckCircleIcon'
                | 'CheckIcon'
                | 'ChevronDoubleDownIcon'
                | 'ChevronDoubleLeftIcon'
                | 'ChevronDoubleRightIcon'
                | 'ChevronDoubleUpIcon'
                | 'ChevronDownIcon'
                | 'ChevronLeftIcon'
                | 'ChevronRightIcon'
                | 'ChevronUpDownIcon'
                | 'ChevronUpIcon'
                | 'CircleStackIcon'
                | 'ClipboardDocumentCheckIcon'
                | 'ClipboardDocumentListIcon'
                | 'ClipboardDocumentIcon'
                | 'ClipboardIcon'
                | 'ClockIcon'
                | 'CloudArrowDownIcon'
                | 'CloudArrowUpIcon'
                | 'CloudIcon'
                | 'CodeBracketSquareIcon'
                | 'CodeBracketIcon'
                | 'Cog6ToothIcon'
                | 'Cog8ToothIcon'
                | 'CogIcon'
                | 'CommandLineIcon'
                | 'ComputerDesktopIcon'
                | 'CpuChipIcon'
                | 'CreditCardIcon'
                | 'CubeTransparentIcon'
                | 'CubeIcon'
                | 'CurrencyBangladeshiIcon'
                | 'CurrencyDollarIcon'
                | 'CurrencyEuroIcon'
                | 'CurrencyPoundIcon'
                | 'CurrencyRupeeIcon'
                | 'CurrencyYenIcon'
                | 'CursorArrowRaysIcon'
                | 'CursorArrowRippleIcon'
                | 'DevicePhoneMobileIcon'
                | 'DeviceTabletIcon'
                | 'DivideIcon'
                | 'DocumentArrowDownIcon'
                | 'DocumentArrowUpIcon'
                | 'DocumentChartBarIcon'
                | 'DocumentCheckIcon'
                | 'DocumentCurrencyBangladeshiIcon'
                | 'DocumentCurrencyDollarIcon'
                | 'DocumentCurrencyEuroIcon'
                | 'DocumentCurrencyPoundIcon'
                | 'DocumentCurrencyRupeeIcon'
                | 'DocumentCurrencyYenIcon'
                | 'DocumentDuplicateIcon'
                | 'DocumentMagnifyingGlassIcon'
                | 'DocumentMinusIcon'
                | 'DocumentPlusIcon'
                | 'DocumentTextIcon'
                | 'DocumentIcon'
                | 'EllipsisHorizontalCircleIcon'
                | 'EllipsisHorizontalIcon'
                | 'EllipsisVerticalIcon'
                | 'EnvelopeOpenIcon'
                | 'EnvelopeIcon'
                | 'EqualsIcon'
                | 'ExclamationCircleIcon'
                | 'ExclamationTriangleIcon'
                | 'EyeDropperIcon'
                | 'EyeSlashIcon'
                | 'EyeIcon'
                | 'FaceFrownIcon'
                | 'FaceSmileIcon'
                | 'FilmIcon'
                | 'FingerPrintIcon'
                | 'FireIcon'
                | 'FlagIcon'
                | 'FolderArrowDownIcon'
                | 'FolderMinusIcon'
                | 'FolderOpenIcon'
                | 'FolderPlusIcon'
                | 'FolderIcon'
                | 'ForwardIcon'
                | 'FunnelIcon'
                | 'GifIcon'
                | 'GiftTopIcon'
                | 'GiftIcon'
                | 'GlobeAltIcon'
                | 'GlobeAmericasIcon'
                | 'GlobeAsiaAustraliaIcon'
                | 'GlobeEuropeAfricaIcon'
                | 'H1Icon'
                | 'H2Icon'
                | 'H3Icon'
                | 'HandRaisedIcon'
                | 'HandThumbDownIcon'
                | 'HandThumbUpIcon'
                | 'HashtagIcon'
                | 'HeartIcon'
                | 'HomeModernIcon'
                | 'HomeIcon'
                | 'IdentificationIcon'
                | 'InboxArrowDownIcon'
                | 'InboxStackIcon'
                | 'InboxIcon'
                | 'InformationCircleIcon'
                | 'ItalicIcon'
                | 'KeyIcon'
                | 'LanguageIcon'
                | 'LifebuoyIcon'
                | 'LightBulbIcon'
                | 'LinkSlashIcon'
                | 'LinkIcon'
                | 'ListBulletIcon'
                | 'LockClosedIcon'
                | 'LockOpenIcon'
                | 'MagnifyingGlassCircleIcon'
                | 'MagnifyingGlassMinusIcon'
                | 'MagnifyingGlassPlusIcon'
                | 'MagnifyingGlassIcon'
                | 'MapPinIcon'
                | 'MapIcon'
                | 'MegaphoneIcon'
                | 'MicrophoneIcon'
                | 'MinusCircleIcon'
                | 'MinusSmallIcon'
                | 'MinusIcon'
                | 'MoonIcon'
                | 'MusicalNoteIcon'
                | 'NewspaperIcon'
                | 'NoSymbolIcon'
                | 'NumberedListIcon'
                | 'PaintBrushIcon'
                | 'PaperAirplaneIcon'
                | 'PaperClipIcon'
                | 'PauseCircleIcon'
                | 'PauseIcon'
                | 'PencilSquareIcon'
                | 'PencilIcon'
                | 'PercentBadgeIcon'
                | 'PhoneArrowDownLeftIcon'
                | 'PhoneArrowUpRightIcon'
                | 'PhoneXMarkIcon'
                | 'PhoneIcon'
                | 'PhotoIcon'
                | 'PlayCircleIcon'
                | 'PlayPauseIcon'
                | 'PlayIcon'
                | 'PlusCircleIcon'
                | 'PlusSmallIcon'
                | 'PlusIcon'
                | 'PowerIcon'
                | 'PresentationChartBarIcon'
                | 'PresentationChartLineIcon'
                | 'PrinterIcon'
                | 'PuzzlePieceIcon'
                | 'QrCodeIcon'
                | 'QuestionMarkCircleIcon'
                | 'QueueListIcon'
                | 'RadioIcon'
                | 'ReceiptPercentIcon'
                | 'ReceiptRefundIcon'
                | 'RectangleGroupIcon'
                | 'RectangleStackIcon'
                | 'RocketLaunchIcon'
                | 'RssIcon'
                | 'ScaleIcon'
                | 'ScissorsIcon'
                | 'ServerStackIcon'
                | 'ServerIcon'
                | 'ShareIcon'
                | 'ShieldCheckIcon'
                | 'ShieldExclamationIcon'
                | 'ShoppingBagIcon'
                | 'ShoppingCartIcon'
                | 'SignalSlashIcon'
                | 'SignalIcon'
                | 'SlashIcon'
                | 'SparklesIcon'
                | 'SpeakerWaveIcon'
                | 'SpeakerXMarkIcon'
                | 'Square2StackIcon'
                | 'Square3Stack3DIcon'
                | 'Squares2X2Icon'
                | 'SquaresPlusIcon'
                | 'StarIcon'
                | 'StopCircleIcon'
                | 'StopIcon'
                | 'StrikethroughIcon'
                | 'SunIcon'
                | 'SwatchIcon'
                | 'TableCellsIcon'
                | 'TagIcon'
                | 'TicketIcon'
                | 'TrashIcon'
                | 'TrophyIcon'
                | 'TruckIcon'
                | 'TvIcon'
                | 'UnderlineIcon'
                | 'UserCircleIcon'
                | 'UserGroupIcon'
                | 'UserMinusIcon'
                | 'UserPlusIcon'
                | 'UserIcon'
                | 'UsersIcon'
                | 'VariableIcon'
                | 'VideoCameraSlashIcon'
                | 'VideoCameraIcon'
                | 'ViewColumnsIcon'
                | 'ViewfinderCircleIcon'
                | 'WalletIcon'
                | 'WifiIcon'
                | 'WindowIcon'
                | 'WrenchScrewdriverIcon'
                | 'WrenchIcon'
                | 'XCircleIcon'
                | 'XMarkIcon';
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'chips';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'projects';
        value: number | Project;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'lab';
        value: number | Lab;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'mux-video';
        value: number | MuxVideo;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  colour?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lab_select".
 */
export interface LabSelect<T extends boolean = true> {
  toolKey?: T;
  enabled?: T;
  order?: T;
  kind?: T;
  group?: T;
  title?: T;
  primaryTag?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  model?: T;
  writeUp?: T;
  blogPostUrl?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  tags?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  readTime?: T;
  publishedAt?: T;
  featured?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  type?: T;
  lifecycle?: T;
  year?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        slideType?: T;
        image?: T;
        muxVideo?: T;
        id?: T;
      };
  description?: T;
  techStack?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  liveUrl?: T;
  codeUrl?: T;
  role?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  tags?: T;
  featured?: T;
  order?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mux-video_select".
 */
export interface MuxVideoSelect<T extends boolean = true> {
  title?: T;
  assetId?: T;
  duration?: T;
  posterTimestamp?: T;
  aspectRatio?: T;
  maxWidth?: T;
  maxHeight?: T;
  playbackOptions?:
    | T
    | {
        playbackId?: T;
        playbackPolicy?: T;
        playbackUrl?: T;
        posterUrl?: T;
        gifUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        chips?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link?: {
          type?: ('reference' | 'sitePage' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null);
          sitePage?: ('home' | 'posts' | 'projects' | 'lab' | 'contact') | null;
          url?: string | null;
          label?: string | null;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline' | 'secondary' | 'miniOutline' | 'link') | null;
          /**
           * Choose the size of the link button.
           */
          size?: 'default' | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Full URL to your GitHub profile (e.g. https://github.com/username).
   */
  githubUrl?: string | null;
  /**
   * Full URL to your LinkedIn profile.
   */
  linkedinUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Name, contact, and status under General; optional home intro under Home; about card under About.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Your full name. Used in the about section and author bios.
   */
  name: string;
  /**
   * Free text status shown with the green dot across the site. e.g. "available for work", "open to freelance", "happily employed".
   */
  statusText: string;
  /**
   * Contact email shown on the contact page and footer.
   */
  email: string;
  /**
   * Your location shown on the contact page and about section.
   */
  location: string;
  /**
   * Main headline on the contact page.
   */
  contactHeadline: string;
  /**
   * Supporting paragraph under the headline.
   */
  contactIntro: string;
  /**
   * Shown next to // typical reply on the contact page.
   */
  contactResponseTime: string;
  /**
   * Optional intro paragraph on the home page, shown below jamjam:~$ and the status.
   */
  homeIntro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Small label shown above the about card (e.g. // about).
   */
  aboutSectionLabel: string;
  /**
   * Main headline inside the about card.
   */
  aboutHeadline: string;
  /**
   * Supporting paragraph below the headline.
   */
  aboutBio: string;
  /**
   * Portrait shown in the about card. Set alt text on the media for accessibility.
   */
  aboutPhoto: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              sitePage?: T;
              url?: T;
              label?: T;
              appearance?: T;
              size?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  githubUrl?: T;
  linkedinUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  statusText?: T;
  email?: T;
  location?: T;
  contactHeadline?: T;
  contactIntro?: T;
  contactResponseTime?: T;
  homeIntro?: T;
  aboutSectionLabel?: T;
  aboutHeadline?: T;
  aboutBio?: T;
  aboutPhoto?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'lab';
          value: number | Lab;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  provider?: ('auto' | 'youtube' | 'vimeo' | 'codepen' | 'figma' | 'iframe') | null;
  url: string;
  title?: string | null;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentCardBlock".
 */
export interface ContentCardBlock {
  /**
   * Note: For best results, use images with the same dimensions/aspect ratio to prevent layout shifts during transitions. Different sized images will still work but may cause the container to resize smoothly.
   */
  media: {
    item: number | Media;
    id?: string | null;
  }[];
  aspectRatio?: ('auto' | 'square' | 'landscape' | 'portrait') | null;
  /**
   * How long each image displays before cycling to the next (in seconds)
   */
  cycleInterval?: number | null;
  /**
   * When enabled, videos will autoplay. When disabled, videos show as thumbnails and play on hover.
   */
  videoAutoplay?: boolean | null;
  enableLink?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    url?: string | null;
    label?: string | null;
  };
  enableFooter?: boolean | null;
  /**
   * Add meta information for each media item. The order should match your media items.
   */
  footerMeta?:
    | {
        title?: string | null;
        description?: string | null;
        location?: string | null;
        customText?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  slides: {
    media: number | Media;
    /**
     * Optional caption for this slide
     */
    caption?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
  }[];
  /**
   * Automatically advance slides
   */
  autoplay?: boolean | null;
  /**
   * Time in milliseconds between slide changes
   */
  autoplayInterval?: number | null;
  /**
   * Show previous/next navigation arrows
   */
  showNavigation?: boolean | null;
  /**
   * Show dot indicators for slide position
   */
  showIndicators?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoCardBlock".
 */
export interface VideoCardBlock {
  /**
   * Select a video from Mux
   */
  video: number | MuxVideo;
  aspectRatio?: ('auto' | 'square' | 'landscape' | 'portrait') | null;
  /**
   * When enabled, videos will autoplay. When disabled, videos show as thumbnails and play on hover.
   */
  videoAutoplay?: boolean | null;
  enableLink?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    url?: string | null;
    label?: string | null;
  };
  enableFooter?: boolean | null;
  /**
   * Add meta information to display in the footer.
   */
  footerMeta?: {
    title?: string | null;
    description?: string | null;
    location?: string | null;
    customText?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoPlayerBlock".
 */
export interface VideoPlayerBlock {
  /**
   * Choose between Mux video asset or external video URL
   */
  videoType: 'mux' | 'external';
  /**
   * Mux asset playback ID
   */
  muxAssetId?: string | null;
  /**
   * YouTube or Vimeo video URL
   */
  externalUrl?: string | null;
  /**
   * Poster image shown before video plays
   */
  poster?: (number | null) | Media;
  /**
   * Automatically play video when page loads
   */
  autoplay?: boolean | null;
  /**
   * Show video player controls
   */
  controls?: boolean | null;
  /**
   * Loop video playback
   */
  loop?: boolean | null;
  /**
   * Start video muted
   */
  muted?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoPlayer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingCardBlock".
 */
export interface PricingCardBlock {
  /**
   * Add one or more pricing cards. Tabs will appear when there are 2+ cards.
   */
  cards?:
    | {
        /**
         * Label displayed on the tab button
         */
        tabLabel: string;
        /**
         * Optional cost indicator (e.g., "$", "€", "A$") Separate with a space if more than one
         */
        costIndicator?: string | null;
        icon:
          | 'AcademicCapIcon'
          | 'AdjustmentsHorizontalIcon'
          | 'AdjustmentsVerticalIcon'
          | 'ArchiveBoxArrowDownIcon'
          | 'ArchiveBoxXMarkIcon'
          | 'ArchiveBoxIcon'
          | 'ArrowDownCircleIcon'
          | 'ArrowDownLeftIcon'
          | 'ArrowDownOnSquareStackIcon'
          | 'ArrowDownOnSquareIcon'
          | 'ArrowDownRightIcon'
          | 'ArrowDownTrayIcon'
          | 'ArrowDownIcon'
          | 'ArrowLeftCircleIcon'
          | 'ArrowLeftEndOnRectangleIcon'
          | 'ArrowLeftOnRectangleIcon'
          | 'ArrowLeftStartOnRectangleIcon'
          | 'ArrowLeftIcon'
          | 'ArrowLongDownIcon'
          | 'ArrowLongLeftIcon'
          | 'ArrowLongRightIcon'
          | 'ArrowLongUpIcon'
          | 'ArrowPathRoundedSquareIcon'
          | 'ArrowPathIcon'
          | 'ArrowRightCircleIcon'
          | 'ArrowRightEndOnRectangleIcon'
          | 'ArrowRightOnRectangleIcon'
          | 'ArrowRightStartOnRectangleIcon'
          | 'ArrowRightIcon'
          | 'ArrowSmallDownIcon'
          | 'ArrowSmallLeftIcon'
          | 'ArrowSmallRightIcon'
          | 'ArrowSmallUpIcon'
          | 'ArrowTopRightOnSquareIcon'
          | 'ArrowTrendingDownIcon'
          | 'ArrowTrendingUpIcon'
          | 'ArrowTurnDownLeftIcon'
          | 'ArrowTurnDownRightIcon'
          | 'ArrowTurnLeftDownIcon'
          | 'ArrowTurnLeftUpIcon'
          | 'ArrowTurnRightDownIcon'
          | 'ArrowTurnRightUpIcon'
          | 'ArrowTurnUpLeftIcon'
          | 'ArrowTurnUpRightIcon'
          | 'ArrowUpCircleIcon'
          | 'ArrowUpLeftIcon'
          | 'ArrowUpOnSquareStackIcon'
          | 'ArrowUpOnSquareIcon'
          | 'ArrowUpRightIcon'
          | 'ArrowUpTrayIcon'
          | 'ArrowUpIcon'
          | 'ArrowUturnDownIcon'
          | 'ArrowUturnLeftIcon'
          | 'ArrowUturnRightIcon'
          | 'ArrowUturnUpIcon'
          | 'ArrowsPointingInIcon'
          | 'ArrowsPointingOutIcon'
          | 'ArrowsRightLeftIcon'
          | 'ArrowsUpDownIcon'
          | 'AtSymbolIcon'
          | 'BackspaceIcon'
          | 'BackwardIcon'
          | 'BanknotesIcon'
          | 'Bars2Icon'
          | 'Bars3BottomLeftIcon'
          | 'Bars3BottomRightIcon'
          | 'Bars3CenterLeftIcon'
          | 'Bars3Icon'
          | 'Bars4Icon'
          | 'BarsArrowDownIcon'
          | 'BarsArrowUpIcon'
          | 'Battery0Icon'
          | 'Battery100Icon'
          | 'Battery50Icon'
          | 'BeakerIcon'
          | 'BellAlertIcon'
          | 'BellSlashIcon'
          | 'BellSnoozeIcon'
          | 'BellIcon'
          | 'BoldIcon'
          | 'BoltSlashIcon'
          | 'BoltIcon'
          | 'BookOpenIcon'
          | 'BookmarkSlashIcon'
          | 'BookmarkSquareIcon'
          | 'BookmarkIcon'
          | 'BriefcaseIcon'
          | 'BugAntIcon'
          | 'BuildingLibraryIcon'
          | 'BuildingOffice2Icon'
          | 'BuildingOfficeIcon'
          | 'BuildingStorefrontIcon'
          | 'CakeIcon'
          | 'CalculatorIcon'
          | 'CalendarDateRangeIcon'
          | 'CalendarDaysIcon'
          | 'CalendarIcon'
          | 'CameraIcon'
          | 'ChartBarSquareIcon'
          | 'ChartBarIcon'
          | 'ChartPieIcon'
          | 'ChatBubbleBottomCenterTextIcon'
          | 'ChatBubbleBottomCenterIcon'
          | 'ChatBubbleLeftEllipsisIcon'
          | 'ChatBubbleLeftRightIcon'
          | 'ChatBubbleLeftIcon'
          | 'ChatBubbleOvalLeftEllipsisIcon'
          | 'ChatBubbleOvalLeftIcon'
          | 'CheckBadgeIcon'
          | 'CheckCircleIcon'
          | 'CheckIcon'
          | 'ChevronDoubleDownIcon'
          | 'ChevronDoubleLeftIcon'
          | 'ChevronDoubleRightIcon'
          | 'ChevronDoubleUpIcon'
          | 'ChevronDownIcon'
          | 'ChevronLeftIcon'
          | 'ChevronRightIcon'
          | 'ChevronUpDownIcon'
          | 'ChevronUpIcon'
          | 'CircleStackIcon'
          | 'ClipboardDocumentCheckIcon'
          | 'ClipboardDocumentListIcon'
          | 'ClipboardDocumentIcon'
          | 'ClipboardIcon'
          | 'ClockIcon'
          | 'CloudArrowDownIcon'
          | 'CloudArrowUpIcon'
          | 'CloudIcon'
          | 'CodeBracketSquareIcon'
          | 'CodeBracketIcon'
          | 'Cog6ToothIcon'
          | 'Cog8ToothIcon'
          | 'CogIcon'
          | 'CommandLineIcon'
          | 'ComputerDesktopIcon'
          | 'CpuChipIcon'
          | 'CreditCardIcon'
          | 'CubeTransparentIcon'
          | 'CubeIcon'
          | 'CurrencyBangladeshiIcon'
          | 'CurrencyDollarIcon'
          | 'CurrencyEuroIcon'
          | 'CurrencyPoundIcon'
          | 'CurrencyRupeeIcon'
          | 'CurrencyYenIcon'
          | 'CursorArrowRaysIcon'
          | 'CursorArrowRippleIcon'
          | 'DevicePhoneMobileIcon'
          | 'DeviceTabletIcon'
          | 'DivideIcon'
          | 'DocumentArrowDownIcon'
          | 'DocumentArrowUpIcon'
          | 'DocumentChartBarIcon'
          | 'DocumentCheckIcon'
          | 'DocumentCurrencyBangladeshiIcon'
          | 'DocumentCurrencyDollarIcon'
          | 'DocumentCurrencyEuroIcon'
          | 'DocumentCurrencyPoundIcon'
          | 'DocumentCurrencyRupeeIcon'
          | 'DocumentCurrencyYenIcon'
          | 'DocumentDuplicateIcon'
          | 'DocumentMagnifyingGlassIcon'
          | 'DocumentMinusIcon'
          | 'DocumentPlusIcon'
          | 'DocumentTextIcon'
          | 'DocumentIcon'
          | 'EllipsisHorizontalCircleIcon'
          | 'EllipsisHorizontalIcon'
          | 'EllipsisVerticalIcon'
          | 'EnvelopeOpenIcon'
          | 'EnvelopeIcon'
          | 'EqualsIcon'
          | 'ExclamationCircleIcon'
          | 'ExclamationTriangleIcon'
          | 'EyeDropperIcon'
          | 'EyeSlashIcon'
          | 'EyeIcon'
          | 'FaceFrownIcon'
          | 'FaceSmileIcon'
          | 'FilmIcon'
          | 'FingerPrintIcon'
          | 'FireIcon'
          | 'FlagIcon'
          | 'FolderArrowDownIcon'
          | 'FolderMinusIcon'
          | 'FolderOpenIcon'
          | 'FolderPlusIcon'
          | 'FolderIcon'
          | 'ForwardIcon'
          | 'FunnelIcon'
          | 'GifIcon'
          | 'GiftTopIcon'
          | 'GiftIcon'
          | 'GlobeAltIcon'
          | 'GlobeAmericasIcon'
          | 'GlobeAsiaAustraliaIcon'
          | 'GlobeEuropeAfricaIcon'
          | 'H1Icon'
          | 'H2Icon'
          | 'H3Icon'
          | 'HandRaisedIcon'
          | 'HandThumbDownIcon'
          | 'HandThumbUpIcon'
          | 'HashtagIcon'
          | 'HeartIcon'
          | 'HomeModernIcon'
          | 'HomeIcon'
          | 'IdentificationIcon'
          | 'InboxArrowDownIcon'
          | 'InboxStackIcon'
          | 'InboxIcon'
          | 'InformationCircleIcon'
          | 'ItalicIcon'
          | 'KeyIcon'
          | 'LanguageIcon'
          | 'LifebuoyIcon'
          | 'LightBulbIcon'
          | 'LinkSlashIcon'
          | 'LinkIcon'
          | 'ListBulletIcon'
          | 'LockClosedIcon'
          | 'LockOpenIcon'
          | 'MagnifyingGlassCircleIcon'
          | 'MagnifyingGlassMinusIcon'
          | 'MagnifyingGlassPlusIcon'
          | 'MagnifyingGlassIcon'
          | 'MapPinIcon'
          | 'MapIcon'
          | 'MegaphoneIcon'
          | 'MicrophoneIcon'
          | 'MinusCircleIcon'
          | 'MinusSmallIcon'
          | 'MinusIcon'
          | 'MoonIcon'
          | 'MusicalNoteIcon'
          | 'NewspaperIcon'
          | 'NoSymbolIcon'
          | 'NumberedListIcon'
          | 'PaintBrushIcon'
          | 'PaperAirplaneIcon'
          | 'PaperClipIcon'
          | 'PauseCircleIcon'
          | 'PauseIcon'
          | 'PencilSquareIcon'
          | 'PencilIcon'
          | 'PercentBadgeIcon'
          | 'PhoneArrowDownLeftIcon'
          | 'PhoneArrowUpRightIcon'
          | 'PhoneXMarkIcon'
          | 'PhoneIcon'
          | 'PhotoIcon'
          | 'PlayCircleIcon'
          | 'PlayPauseIcon'
          | 'PlayIcon'
          | 'PlusCircleIcon'
          | 'PlusSmallIcon'
          | 'PlusIcon'
          | 'PowerIcon'
          | 'PresentationChartBarIcon'
          | 'PresentationChartLineIcon'
          | 'PrinterIcon'
          | 'PuzzlePieceIcon'
          | 'QrCodeIcon'
          | 'QuestionMarkCircleIcon'
          | 'QueueListIcon'
          | 'RadioIcon'
          | 'ReceiptPercentIcon'
          | 'ReceiptRefundIcon'
          | 'RectangleGroupIcon'
          | 'RectangleStackIcon'
          | 'RocketLaunchIcon'
          | 'RssIcon'
          | 'ScaleIcon'
          | 'ScissorsIcon'
          | 'ServerStackIcon'
          | 'ServerIcon'
          | 'ShareIcon'
          | 'ShieldCheckIcon'
          | 'ShieldExclamationIcon'
          | 'ShoppingBagIcon'
          | 'ShoppingCartIcon'
          | 'SignalSlashIcon'
          | 'SignalIcon'
          | 'SlashIcon'
          | 'SparklesIcon'
          | 'SpeakerWaveIcon'
          | 'SpeakerXMarkIcon'
          | 'Square2StackIcon'
          | 'Square3Stack3DIcon'
          | 'Squares2X2Icon'
          | 'SquaresPlusIcon'
          | 'StarIcon'
          | 'StopCircleIcon'
          | 'StopIcon'
          | 'StrikethroughIcon'
          | 'SunIcon'
          | 'SwatchIcon'
          | 'TableCellsIcon'
          | 'TagIcon'
          | 'TicketIcon'
          | 'TrashIcon'
          | 'TrophyIcon'
          | 'TruckIcon'
          | 'TvIcon'
          | 'UnderlineIcon'
          | 'UserCircleIcon'
          | 'UserGroupIcon'
          | 'UserMinusIcon'
          | 'UserPlusIcon'
          | 'UserIcon'
          | 'UsersIcon'
          | 'VariableIcon'
          | 'VideoCameraSlashIcon'
          | 'VideoCameraIcon'
          | 'ViewColumnsIcon'
          | 'ViewfinderCircleIcon'
          | 'WalletIcon'
          | 'WifiIcon'
          | 'WindowIcon'
          | 'WrenchScrewdriverIcon'
          | 'WrenchIcon'
          | 'XCircleIcon'
          | 'XMarkIcon';
        title: string;
        description?: string | null;
        /**
         * Price text (e.g., "A$450", "$450", "450€")
         */
        startingPrice: string;
        /**
         * Additional pricing information (e.g., "per month", "per year")
         */
        priceDescription?: string | null;
        includes?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Text displayed on the link button
         */
        linkButtonText?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null);
          url?: string | null;
          label?: string | null;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
          /**
           * Choose the size of the link button.
           */
          size?: ('default' | 'lg') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoCTABlock".
 */
export interface BentoCTABlock {
  /**
   * The main image displayed in the left BentoBox
   */
  mainImage: number | Media;
  /**
   * Quotes to display in the carousel
   */
  quotes: {
    quote: string;
    /**
     * Optional icon to display next to the quote
     */
    icon?:
      | (
          | 'AcademicCapIcon'
          | 'AdjustmentsHorizontalIcon'
          | 'AdjustmentsVerticalIcon'
          | 'ArchiveBoxArrowDownIcon'
          | 'ArchiveBoxXMarkIcon'
          | 'ArchiveBoxIcon'
          | 'ArrowDownCircleIcon'
          | 'ArrowDownLeftIcon'
          | 'ArrowDownOnSquareStackIcon'
          | 'ArrowDownOnSquareIcon'
          | 'ArrowDownRightIcon'
          | 'ArrowDownTrayIcon'
          | 'ArrowDownIcon'
          | 'ArrowLeftCircleIcon'
          | 'ArrowLeftEndOnRectangleIcon'
          | 'ArrowLeftOnRectangleIcon'
          | 'ArrowLeftStartOnRectangleIcon'
          | 'ArrowLeftIcon'
          | 'ArrowLongDownIcon'
          | 'ArrowLongLeftIcon'
          | 'ArrowLongRightIcon'
          | 'ArrowLongUpIcon'
          | 'ArrowPathRoundedSquareIcon'
          | 'ArrowPathIcon'
          | 'ArrowRightCircleIcon'
          | 'ArrowRightEndOnRectangleIcon'
          | 'ArrowRightOnRectangleIcon'
          | 'ArrowRightStartOnRectangleIcon'
          | 'ArrowRightIcon'
          | 'ArrowSmallDownIcon'
          | 'ArrowSmallLeftIcon'
          | 'ArrowSmallRightIcon'
          | 'ArrowSmallUpIcon'
          | 'ArrowTopRightOnSquareIcon'
          | 'ArrowTrendingDownIcon'
          | 'ArrowTrendingUpIcon'
          | 'ArrowTurnDownLeftIcon'
          | 'ArrowTurnDownRightIcon'
          | 'ArrowTurnLeftDownIcon'
          | 'ArrowTurnLeftUpIcon'
          | 'ArrowTurnRightDownIcon'
          | 'ArrowTurnRightUpIcon'
          | 'ArrowTurnUpLeftIcon'
          | 'ArrowTurnUpRightIcon'
          | 'ArrowUpCircleIcon'
          | 'ArrowUpLeftIcon'
          | 'ArrowUpOnSquareStackIcon'
          | 'ArrowUpOnSquareIcon'
          | 'ArrowUpRightIcon'
          | 'ArrowUpTrayIcon'
          | 'ArrowUpIcon'
          | 'ArrowUturnDownIcon'
          | 'ArrowUturnLeftIcon'
          | 'ArrowUturnRightIcon'
          | 'ArrowUturnUpIcon'
          | 'ArrowsPointingInIcon'
          | 'ArrowsPointingOutIcon'
          | 'ArrowsRightLeftIcon'
          | 'ArrowsUpDownIcon'
          | 'AtSymbolIcon'
          | 'BackspaceIcon'
          | 'BackwardIcon'
          | 'BanknotesIcon'
          | 'Bars2Icon'
          | 'Bars3BottomLeftIcon'
          | 'Bars3BottomRightIcon'
          | 'Bars3CenterLeftIcon'
          | 'Bars3Icon'
          | 'Bars4Icon'
          | 'BarsArrowDownIcon'
          | 'BarsArrowUpIcon'
          | 'Battery0Icon'
          | 'Battery100Icon'
          | 'Battery50Icon'
          | 'BeakerIcon'
          | 'BellAlertIcon'
          | 'BellSlashIcon'
          | 'BellSnoozeIcon'
          | 'BellIcon'
          | 'BoldIcon'
          | 'BoltSlashIcon'
          | 'BoltIcon'
          | 'BookOpenIcon'
          | 'BookmarkSlashIcon'
          | 'BookmarkSquareIcon'
          | 'BookmarkIcon'
          | 'BriefcaseIcon'
          | 'BugAntIcon'
          | 'BuildingLibraryIcon'
          | 'BuildingOffice2Icon'
          | 'BuildingOfficeIcon'
          | 'BuildingStorefrontIcon'
          | 'CakeIcon'
          | 'CalculatorIcon'
          | 'CalendarDateRangeIcon'
          | 'CalendarDaysIcon'
          | 'CalendarIcon'
          | 'CameraIcon'
          | 'ChartBarSquareIcon'
          | 'ChartBarIcon'
          | 'ChartPieIcon'
          | 'ChatBubbleBottomCenterTextIcon'
          | 'ChatBubbleBottomCenterIcon'
          | 'ChatBubbleLeftEllipsisIcon'
          | 'ChatBubbleLeftRightIcon'
          | 'ChatBubbleLeftIcon'
          | 'ChatBubbleOvalLeftEllipsisIcon'
          | 'ChatBubbleOvalLeftIcon'
          | 'CheckBadgeIcon'
          | 'CheckCircleIcon'
          | 'CheckIcon'
          | 'ChevronDoubleDownIcon'
          | 'ChevronDoubleLeftIcon'
          | 'ChevronDoubleRightIcon'
          | 'ChevronDoubleUpIcon'
          | 'ChevronDownIcon'
          | 'ChevronLeftIcon'
          | 'ChevronRightIcon'
          | 'ChevronUpDownIcon'
          | 'ChevronUpIcon'
          | 'CircleStackIcon'
          | 'ClipboardDocumentCheckIcon'
          | 'ClipboardDocumentListIcon'
          | 'ClipboardDocumentIcon'
          | 'ClipboardIcon'
          | 'ClockIcon'
          | 'CloudArrowDownIcon'
          | 'CloudArrowUpIcon'
          | 'CloudIcon'
          | 'CodeBracketSquareIcon'
          | 'CodeBracketIcon'
          | 'Cog6ToothIcon'
          | 'Cog8ToothIcon'
          | 'CogIcon'
          | 'CommandLineIcon'
          | 'ComputerDesktopIcon'
          | 'CpuChipIcon'
          | 'CreditCardIcon'
          | 'CubeTransparentIcon'
          | 'CubeIcon'
          | 'CurrencyBangladeshiIcon'
          | 'CurrencyDollarIcon'
          | 'CurrencyEuroIcon'
          | 'CurrencyPoundIcon'
          | 'CurrencyRupeeIcon'
          | 'CurrencyYenIcon'
          | 'CursorArrowRaysIcon'
          | 'CursorArrowRippleIcon'
          | 'DevicePhoneMobileIcon'
          | 'DeviceTabletIcon'
          | 'DivideIcon'
          | 'DocumentArrowDownIcon'
          | 'DocumentArrowUpIcon'
          | 'DocumentChartBarIcon'
          | 'DocumentCheckIcon'
          | 'DocumentCurrencyBangladeshiIcon'
          | 'DocumentCurrencyDollarIcon'
          | 'DocumentCurrencyEuroIcon'
          | 'DocumentCurrencyPoundIcon'
          | 'DocumentCurrencyRupeeIcon'
          | 'DocumentCurrencyYenIcon'
          | 'DocumentDuplicateIcon'
          | 'DocumentMagnifyingGlassIcon'
          | 'DocumentMinusIcon'
          | 'DocumentPlusIcon'
          | 'DocumentTextIcon'
          | 'DocumentIcon'
          | 'EllipsisHorizontalCircleIcon'
          | 'EllipsisHorizontalIcon'
          | 'EllipsisVerticalIcon'
          | 'EnvelopeOpenIcon'
          | 'EnvelopeIcon'
          | 'EqualsIcon'
          | 'ExclamationCircleIcon'
          | 'ExclamationTriangleIcon'
          | 'EyeDropperIcon'
          | 'EyeSlashIcon'
          | 'EyeIcon'
          | 'FaceFrownIcon'
          | 'FaceSmileIcon'
          | 'FilmIcon'
          | 'FingerPrintIcon'
          | 'FireIcon'
          | 'FlagIcon'
          | 'FolderArrowDownIcon'
          | 'FolderMinusIcon'
          | 'FolderOpenIcon'
          | 'FolderPlusIcon'
          | 'FolderIcon'
          | 'ForwardIcon'
          | 'FunnelIcon'
          | 'GifIcon'
          | 'GiftTopIcon'
          | 'GiftIcon'
          | 'GlobeAltIcon'
          | 'GlobeAmericasIcon'
          | 'GlobeAsiaAustraliaIcon'
          | 'GlobeEuropeAfricaIcon'
          | 'H1Icon'
          | 'H2Icon'
          | 'H3Icon'
          | 'HandRaisedIcon'
          | 'HandThumbDownIcon'
          | 'HandThumbUpIcon'
          | 'HashtagIcon'
          | 'HeartIcon'
          | 'HomeModernIcon'
          | 'HomeIcon'
          | 'IdentificationIcon'
          | 'InboxArrowDownIcon'
          | 'InboxStackIcon'
          | 'InboxIcon'
          | 'InformationCircleIcon'
          | 'ItalicIcon'
          | 'KeyIcon'
          | 'LanguageIcon'
          | 'LifebuoyIcon'
          | 'LightBulbIcon'
          | 'LinkSlashIcon'
          | 'LinkIcon'
          | 'ListBulletIcon'
          | 'LockClosedIcon'
          | 'LockOpenIcon'
          | 'MagnifyingGlassCircleIcon'
          | 'MagnifyingGlassMinusIcon'
          | 'MagnifyingGlassPlusIcon'
          | 'MagnifyingGlassIcon'
          | 'MapPinIcon'
          | 'MapIcon'
          | 'MegaphoneIcon'
          | 'MicrophoneIcon'
          | 'MinusCircleIcon'
          | 'MinusSmallIcon'
          | 'MinusIcon'
          | 'MoonIcon'
          | 'MusicalNoteIcon'
          | 'NewspaperIcon'
          | 'NoSymbolIcon'
          | 'NumberedListIcon'
          | 'PaintBrushIcon'
          | 'PaperAirplaneIcon'
          | 'PaperClipIcon'
          | 'PauseCircleIcon'
          | 'PauseIcon'
          | 'PencilSquareIcon'
          | 'PencilIcon'
          | 'PercentBadgeIcon'
          | 'PhoneArrowDownLeftIcon'
          | 'PhoneArrowUpRightIcon'
          | 'PhoneXMarkIcon'
          | 'PhoneIcon'
          | 'PhotoIcon'
          | 'PlayCircleIcon'
          | 'PlayPauseIcon'
          | 'PlayIcon'
          | 'PlusCircleIcon'
          | 'PlusSmallIcon'
          | 'PlusIcon'
          | 'PowerIcon'
          | 'PresentationChartBarIcon'
          | 'PresentationChartLineIcon'
          | 'PrinterIcon'
          | 'PuzzlePieceIcon'
          | 'QrCodeIcon'
          | 'QuestionMarkCircleIcon'
          | 'QueueListIcon'
          | 'RadioIcon'
          | 'ReceiptPercentIcon'
          | 'ReceiptRefundIcon'
          | 'RectangleGroupIcon'
          | 'RectangleStackIcon'
          | 'RocketLaunchIcon'
          | 'RssIcon'
          | 'ScaleIcon'
          | 'ScissorsIcon'
          | 'ServerStackIcon'
          | 'ServerIcon'
          | 'ShareIcon'
          | 'ShieldCheckIcon'
          | 'ShieldExclamationIcon'
          | 'ShoppingBagIcon'
          | 'ShoppingCartIcon'
          | 'SignalSlashIcon'
          | 'SignalIcon'
          | 'SlashIcon'
          | 'SparklesIcon'
          | 'SpeakerWaveIcon'
          | 'SpeakerXMarkIcon'
          | 'Square2StackIcon'
          | 'Square3Stack3DIcon'
          | 'Squares2X2Icon'
          | 'SquaresPlusIcon'
          | 'StarIcon'
          | 'StopCircleIcon'
          | 'StopIcon'
          | 'StrikethroughIcon'
          | 'SunIcon'
          | 'SwatchIcon'
          | 'TableCellsIcon'
          | 'TagIcon'
          | 'TicketIcon'
          | 'TrashIcon'
          | 'TrophyIcon'
          | 'TruckIcon'
          | 'TvIcon'
          | 'UnderlineIcon'
          | 'UserCircleIcon'
          | 'UserGroupIcon'
          | 'UserMinusIcon'
          | 'UserPlusIcon'
          | 'UserIcon'
          | 'UsersIcon'
          | 'VariableIcon'
          | 'VideoCameraSlashIcon'
          | 'VideoCameraIcon'
          | 'ViewColumnsIcon'
          | 'ViewfinderCircleIcon'
          | 'WalletIcon'
          | 'WifiIcon'
          | 'WindowIcon'
          | 'WrenchScrewdriverIcon'
          | 'WrenchIcon'
          | 'XCircleIcon'
          | 'XMarkIcon'
        )
      | null;
    id?: string | null;
  }[];
  /**
   * Automatically advance through quotes
   */
  autoplay?: boolean | null;
  /**
   * Time in milliseconds between quote changes
   */
  autoplayInterval?: number | null;
  /**
   * Show dot indicators for quote position
   */
  showIndicators?: boolean | null;
  /**
   * Call-to-action button displayed below the quotes
   */
  ctaLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    url?: string | null;
    label?: string | null;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline' | 'white') | null;
    /**
     * Choose the size of the link button.
     */
    size?: 'default' | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'bentoCTA';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null);
          url?: string | null;
          label?: string | null;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
          /**
           * Choose the size of the link button.
           */
          size?: 'default' | null;
        };
        children?:
          | (
              | ContentCardBlock
              | CarouselBlock
              | VideoCardBlock
              | VideoPlayerBlock
              | FormBlock
              | PricingCardBlock
              | BentoCTABlock
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}